{% set name = "datamol" %}
{% set version = "0.9.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamol-{{ version }}.tar.gz
  sha256: 6ca03ee025c457601aeae65c9b9cd96dece2854734678d5527c744020dae1128

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pip
    - tqdm
    - loguru
    - joblib
    - platformdirs
    - fsspec >=2021.9
    - packaging
    - typing_extensions

    # Scientific
    - pandas
    - numpy
    - scipy
    - pillow
    - matplotlib-base
    - scikit-learn

    # Chemistry
    - rdkit >=2021.09
    - selfies

test:
  imports:
    - datamol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datamol-org/datamol
  summary: A python library to work with molecules. Built on top of RDKit.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
