{% set name = "datamol" %}
{% set version = "0.7.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamol-{{ version }}.tar.gz
  sha256: 6376212c36f6c423f8fdc28d3df3a3ea499fa9a3ed5dbfe8abe5823abea7f921

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pip
    - tqdm
    - loguru
    - joblib
    - appdirs
    - fsspec >=2021.9
    - packaging

    # Scientific
    - pandas
    - numpy
    - scipy
    - pillow
    - matplotlib-base
    - scikit-learn

    # Chemistry
    - rdkit >=2021.09
    - selfies

test:
  imports:
    - datamol
  # disable because rdkit in setup.py is no detected
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/datamol-org/datamol
  summary: A python library to work with molecules. Built on top of RDKit.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
