{% set name = "datamol" %}
{% set version = "0.3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamol-{{ version }}.tar.gz
  sha256: 05a3b968007377d0b27c1b42b57eb6fd8d4de0c1751adabd764c0747c14c3800

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec >=0.8.0
    - joblib
    - loguru
    - numpy
    - pandas
    - pillow
    - python >=3.7
    - scipy
    - selfies
    - tqdm
    - rdkit >=2020.09
    - s3fs
    - gcsfs

test:
 requires:
    - pytest >=6.0
    - pytest-cov
  source_files:
    - tests/
    - pyproject.toml
  imports:
    - datamol
  commands:
    - pip check
    - pytest
  requires:
    - pip

about:
  home: https://github.com/datamol-org/datamol
  summary: A python library to work with molecules. Built on top of RDKit.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
